---
title: "PSTAT 296A - dataset"
author: "Kristy Cheng"
date: "10/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r reading files, cache=TRUE}
setwd("/Users/kristy/Desktop")
library(readxl)
library(tidyverse)

tb1 = read_xlsx("Ucsb_06302018Part1_RowID.xlsx")
tb2 = read_xlsx("Ucsb_06302018Part2_RowID.xlsx")
```

```{r}
tb1 = as.tibble(tb1)
tb2 = as.tibble(tb2)
table(tb1$ProgramYear)
table(tb2$ProgramYear)
```

```{r Evaluation Date}
#summary of evaluation date in part 1 and part 2
table(tb1$`Evaluation Date`)
table(tb2$`Evaluation Date`)
```

```{r Claim Type}
#summary of Claim Type in part 1 and part 2
table(tb1$`Claim Type`)
table(tb2$`Claim Type`)

#Unique categories of Claim Type 
u1=unique(tb1$`Claim Type`)
u2=unique(tb2$`Claim Type`)
unique(c(u1,u2))
```
```{r Settlement Type}
#Summary of Settlement Type in part 1 and 2
table(tb1$`Settlement Type`)
table(tb2$`Settlement Type`)
```

{r inserts row ID}
tb1$rowID <- seq.int(nrow(tb1))
tb2$rowid <- seq.int(nrow(tb2))
names(tb2)[names(tb2)=="rowid"] = "rowID"


{r select variables}
tb1_2 = tb1[,c(118,1:117)]
tb2_2 = tb2[,c(118,1:117)]


```{r}
library(dplyr)
```


Keeping the following Claim Types only:  Temp Disability, Future Medical, Indemnity and Death. 
```{r}
tb1_2 = filter(tb1_2, `Claim Type` %in% c("Temp Disability","Future Medical"))
tb2_2 = filter(tb2_2, `Claim Type` %in% c("Temp Disability","Future Medical", "Indemnity", "Death"))
```

Delete data that has program year 1994-1995 or prior. (no filtering needed for part 1)
```{r}
tb2_2 = filter(tb2_2, ProgramYear %in% c("1995-1996","1996-1997", "1997-1998","1998-1999","1999-2000","2000-2001","2001-2002","2002-2003","2003-2004","2004-2005","2005-2006","2006-2007","2007-2008","2008-2009","2009-2010","2010-2011","2011-2012","2012-2013","2013-2014","2014-2015","2015-2016","2016-2017","2017-2018"))
```

```{r reformat dates}
#Transform variable "Date Received" into Date format
tb2_2$`Date Received` = as.numeric(tb2_2$`Date Received`)
tb2_2$`Date Received` = as.Date(tb2_2$`Date Received`, origin = "1899-12-30")
```

```{r combine files}
#combine dataset part 1 and part 2
tb_combine = rbind(tb1_2, tb2_2)
head(tb_combine)
```

```{r check unique}
#dimension of the combined dataset
dim(tb_combine)
tb_combine = as.data.frame(tb_combine)
dim(tb_combine)

c1=tb_combine[,1]
length(c1)
length(unique(c1))

summary(tb_combine)

#uns is a vector containing the number of unique values in each columns
uns = NULL
for(i in 1:118){
  ci = tb_combine[,i]
  uns = c(uns, length(unique(ci)))
  }
uns

#tb_combine2 eliminates variables with only one single value across observations(i.e. uns == 1)
tb_combine2 = tb_combine[,-which(uns == 1)]
dim(tb_combine2)

'The for loop creates vector col_delete, 
which contains the column number that is being deleted'
col_delete = NULL
for (i in 1:118) {
  if (uns[i] == 1) {
    col_delete = c(col_delete, i)
  }
}
col_delete

table(tb_combine[,102])
```
